[project]
name = "directory-project"
version = "0.1.0"
description = "In-memory directory"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
